In [2]:
import pandas as pd

df = pd.read_csv('data/nyc_weather_dirty.csv')
df.isna().sum()
df.columns = ['date and time', 'temperature', 'humidity','wind speed', 'cloud cover','amount of precipitation']
df.head()

,date and time,temperature,humidity,wind speed,cloud cover,amount of precipitation
0,2019-01-01 00:00:00,8.700000,97.000000,16.100000,100%.,7.1
1,2019-01-01 03:00:00,12.366667,94.333333,26.600000,100%.,0.4
2,2019-01-01 06:00:00,13.600000,90.000000,29.633333,70 – 80%.,0.0
3,2019-01-01 09:00:00,13.933333,74.333333,32.400000,100%.,0.0
4,2019-01-01 12:00:00,11.500000,60.333333,33.400000,70 – 80%.,0.0

In [3]:
df['cloud cover'].value_counts()

cloud cover
100%.           99
no clouds       55
70 – 80%.       36
20–30%.         28
50%.            22
??               1
weird_value1     1
undefined        1
broken_data      1
Name: count, dtype: int64

In [4]:
df.to_csv('data/nyc_weather_missing_values.csv', index=False)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

dataset_dict = {
   'Outlook': ['sunny', 'sunny', 'overcast', 'rain', 'rain', 'rain', 'overcast', 
               'sunny', 'sunny', 'rain', 'sunny', 'overcast', 'overcast', 'rain',
               'sunny', 'overcast', 'rain', 'sunny', 'sunny', 'rain', 'overcast',
               'rain', 'sunny', 'overcast', 'sunny', 'overcast', 'rain', 'overcast'],
   'Temp.': [85.0, 80.0, 83.0, 70.0, 68.0, 65.0, 64.0, 72.0, 69.0, 75.0, 75.0,
             72.0, 81.0, 71.0, 81.0, 74.0, 76.0, 78.0, 82.0, 67.0, 85.0, 73.0,
             88.0, 77.0, 79.0, 80.0, 66.0, 84.0],
   'Humid.': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0,
              90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0,
              65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
   'Wind': [False, True, False, False, False, True, True, False, False, False, True,
            True, False, True, True, False, False, True, False, True, True, False,
            True, False, False, True, False, False],
   'Num_Players': [52, 39, 43, 37, 28, 19, 43, 47, 56, 33, 49, 23, 42, 13, 33, 29,
                   25, 51, 41, 14, 34, 29, 49, 36, 57, 21, 23, 41]
}

df = pd.DataFrame(dataset_dict)

df.info()
print(f'\n' * 1)
print(df['Outlook'].value_counts())

df = pd.get_dummies(df, prefix="", prefix_sep="", dtype='int')
col_names = ['overcast', 'rain', 'sunny', 'Temp.', 'Humid.', 'Wind', 'Num_Players']
df = df[col_names]
df['Wind'] = df['Wind'].astype(int)

X, y = df.drop(labels='Num_Players', axis=1), df['Num_Players']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.5, shuffle=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      28 non-null     object
 1   Temp.        28 non-null     float64
 2   Humid.       28 non-null     float64
 3   Wind         28 non-null     bool
 4   Num_Players  28 non-null     int64
dtypes: bool(1), float64(2), int64(1), object(1)
memory usage: 1.0+ KB


Outlook
sunny       10
overcast     9
rain         9
Name: count, dtype: int64

In [3]:
df_train = pd.concat([X_train, y_train], axis=1)
df_train

    overcast  rain  sunny  Temp.  Humid.  Wind  Num_Players
0          0     0      1   85.0    85.0     0           52
1          0     0      1   80.0    90.0     1           39
2          1     0      0   83.0    78.0     0           43
3          0     1      0   70.0    96.0     0           37
4          0     1      0   68.0    80.0     0           28
5          0     1      0   65.0    70.0     1           19
6          1     0      0   64.0    65.0     1           43
7          0     0      1   72.0    95.0     0           47
8          0     0      1   69.0    70.0     0           56
9          0     1      0   75.0    80.0     0           33
10         0     0      1   75.0    70.0     1           49
11         1     0      0   72.0    90.0     1           23
12         1     0      0   81.0    75.0     0           42
13         0     1      0   71.0    80.0     1           13

In [4]:
y_mean = y_train.mean().round(2)
print(f'y_mean: {y_mean}')

r1 = y_train - y_mean
r1.round(2)

y_mean: 37.43

0     14.57
1      1.57
2      5.57
3     -0.43
4     -9.43
5    -18.43
6      5.57
7      9.57
8     18.57
9     -4.43
10    11.57
11   -14.43
12     4.57
13   -24.43
Name: Num_Players, dtype: float64

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

reg = DecisionTreeRegressor(criterion='squared_error', max_depth=3)
reg.fit(X_train, r1)
y_1 = reg.predict(X_train)

pd.DataFrame(y_1, columns=['y_1']).round(2)

      y_1
0   14.90
1    5.57
2    5.24
3   -2.43
4   -9.43
5  -18.43
6    5.24
7    5.57
8   14.90
9   -2.43
10  14.90
11 -14.43
12   5.24
13 -24.43